export type CurrencyType = {
  value: string
  label: string
  symbol: string
  locale: string
}

export const currencies: CurrencyType[] = [
  {
    value: 'USD',
    label: '$ Dollar',
    symbol: '$',
    locale: 'en-US',
  },
  {
    value: 'EUR',
    label: '€ Euro',
    symbol: '€',
    locale: 'de-DE',
  },
  {
    value: 'JPY',
    label: '¥ Yen',
    symbol: '¥',
    locale: 'ja-JP',
  },
  {
    value: 'GBP',
    label: '£ Pound',
    symbol: '£',
    locale: 'en-GB',
  },
  {
    value: 'AUD',
    label: 'A$ Australian Dollar',
    symbol: 'A$',
    locale: 'en-AU',
  },
  {
    value: 'CAD',
    label: 'C$ Canadian Dollar',
    symbol: 'C$',
    locale: 'en-CA',
  },
  {
    value: 'CHF',
    label: 'CHF Swiss Franc',
    symbol: 'CHF',
    locale: 'de-CH',
  },
  {
    value: 'CNY',
    label: '¥ Yuan',
    symbol: '¥',
    locale: 'zh-CN',
  },
  {
    value: 'INR',
    label: '₹ Indian Rupee',
    symbol: '₹',
    locale: 'en-IN',
  },
  {
    value: 'SGD',
    label: 'S$ Singapore Dollar',
    symbol: 'S$',
    locale: 'en-SG',
  },
  {
    value: 'NZD',
    label: 'NZ$ New Zealand Dollar',
    symbol: 'NZ$',
    locale: 'en-NZ',
  },
  {
    value: 'KRW',
    label: '₩ Won',
    symbol: '₩',
    locale: 'ko-KR',
  },
  {
    value: 'RUB',
    label: '₽ Russian Ruble',
    symbol: '₽',
    locale: 'ru-RU',
  },
  {
    value: 'ZAR',
    label: 'R South African Rand',
    symbol: 'R',
    locale: 'en-ZA',
  },
  {
    value: 'BRL',
    label: 'R$ Brazilian Real',
    symbol: 'R$',
    locale: 'pt-BR',
  },
  {
    value: 'MXN',
    label: 'Mex$ Mexican Peso',
    symbol: 'Mex$',
    locale: 'es-MX',
  },
  {
    value: 'SEK',
    label: 'kr Swedish Krona',
    symbol: 'kr',
    locale: 'sv-SE',
  },
  {
    value: 'NOK',
    label: 'kr Norwegian Krone',
    symbol: 'kr',
    locale: 'nb-NO',
  },
  {
    value: 'DKK',
    label: 'kr Danish Krone',
    symbol: 'kr',
    locale: 'da-DK',
  },
  {
    value: 'TRY',
    label: '₺ Turkish Lira',
    symbol: '₺',
    locale: 'tr-TR',
  },
  {
    value: 'HKD',
    label: 'HK$ Hong Kong Dollar',
    symbol: 'HK$',
    locale: 'en-HK',
  },
  {
    value: 'THB',
    label: '฿ Thai Baht',
    symbol: '฿',
    locale: 'th-TH',
  },
  {
    value: 'IDR',
    label: 'Rp Indonesian Rupiah',
    symbol: 'Rp',
    locale: 'id-ID',
  },
  {
    value: 'MYR',
    label: 'RM Malaysian Ringgit',
    symbol: 'RM',
    locale: 'ms-MY',
  },
  {
    value: 'PHP',
    label: '₱ Philippine Peso',
    symbol: '₱',
    locale: 'en-PH',
  },
  {
    value: 'PLN',
    label: 'zł Polish Złoty',
    symbol: 'zł',
    locale: 'pl-PL',
  },
  {
    value: 'CZK',
    label: 'Kč Czech Koruna',
    symbol: 'Kč',
    locale: 'cs-CZ',
  },
  {
    value: 'HUF',
    label: 'Ft Hungarian Forint',
    symbol: 'Ft',
    locale: 'hu-HU',
  },
  {
    value: 'ILS',
    label: '₪ Israeli Shekel',
    symbol: '₪',
    locale: 'he-IL',
  },
  {
    value: 'AED',
    label: 'د.إ UAE Dirham',
    symbol: 'د.إ',
    locale: 'ar-AE',
  },
  {
    value: 'SAR',
    label: '﷼ Saudi Riyal',
    symbol: '﷼',
    locale: 'ar-SA',
  },
  {
    value: 'QAR',
    label: '﷼ Qatari Riyal',
    symbol: '﷼',
    locale: 'ar-QA',
  },
  {
    value: 'KWD',
    label: 'د.ك Kuwaiti Dinar',
    symbol: 'د.ك',
    locale: 'ar-KW',
  },
  {
    value: 'EGP',
    label: '£ Egyptian Pound',
    symbol: '£',
    locale: 'ar-EG',
  },
  {
    value: 'PKR',
    label: '₨ Pakistani Rupee',
    symbol: '₨',
    locale: 'ur-PK',
  },
  {
    value: 'BDT',
    label: '৳ Bangladeshi Taka',
    symbol: '৳',
    locale: 'bn-BD',
  },
  {
    value: 'LKR',
    label: '₨ Sri Lankan Rupee',
    symbol: '₨',
    locale: 'si-LK',
  },
  {
    value: 'NPR',
    label: '₨ Nepalese Rupee',
    symbol: '₨',
    locale: 'ne-NP',
  },
  {
    value: 'VND',
    label: '₫ Vietnamese Dong',
    symbol: '₫',
    locale: 'vi-VN',
  },
  {
    value: 'MMK',
    label: 'K Burmese Kyat',
    symbol: 'K',
    locale: 'my-MM',
  },
  {
    value: 'KHR',
    label: '៛ Cambodian Riel',
    symbol: '៛',
    locale: 'km-KH',
  },
  {
    value: 'LAK',
    label: '₭ Lao Kip',
    symbol: '₭',
    locale: 'lo-LA',
  },
  {
    value: 'MNT',
    label: '₮ Mongolian Tugrik',
    symbol: '₮',
    locale: 'mn-MN',
  },
  {
    value: 'UZS',
    label: 'Uzbekistani Som',
    symbol: 'UZS',
    locale: 'uz-UZ',
  },
  {
    value: 'KZT',
    label: '₸ Kazakhstani Tenge',
    symbol: '₸',
    locale: 'kk-KZ',
  },
  {
    value: 'TWD',
    label: 'NT$ New Taiwan Dollar',
    symbol: 'NT$',
    locale: 'zh-TW',
  },
  {
    value: 'CLP',
    label: 'CLP$ Chilean Peso',
    symbol: 'CLP$',
    locale: 'es-CL',
  },
  {
    value: 'COP',
    label: 'COL$ Colombian Peso',
    symbol: 'COL$',
    locale: 'es-CO',
  },
  {
    value: 'PEN',
    label: 'S/. Peruvian Sol',
    symbol: 'S/.',
    locale: 'es-PE',
  },
  {
    value: 'ARS',
    label: 'AR$ Argentine Peso',
    symbol: 'AR$',
    locale: 'es-AR',
  },
  {
    value: 'BOB',
    label: 'Bs Bolivian Boliviano',
    symbol: 'Bs',
    locale: 'es-BO',
  },
  {
    value: 'UYU',
    label: '$U Uruguayan Peso',
    symbol: '$U',
    locale: 'es-UY',
  },
  {
    value: 'PYG',
    label: '₲ Paraguayan Guarani',
    symbol: '₲',
    locale: 'es-PY',
  },
  {
    value: 'CRC',
    label: '₡ Costa Rican Colón',
    symbol: '₡',
    locale: 'es-CR',
  },
  {
    value: 'DOP',
    label: 'RD$ Dominican Peso',
    symbol: 'RD$',
    locale: 'es-DO',
  },
  {
    value: 'GTQ',
    label: 'Q Guatemalan Quetzal',
    symbol: 'Q',
    locale: 'es-GT',
  },
  {
    value: 'HNL',
    label: 'L Honduran Lempira',
    symbol: 'L',
    locale: 'es-HN',
  },
  {
    value: 'NIO',
    label: 'C$ Nicaraguan Córdoba',
    symbol: 'C$',
    locale: 'es-NI',
  },
  {
    value: 'PAB',
    label: 'B/. Panamanian Balboa',
    symbol: 'B/.',
    locale: 'es-PA',
  },
  {
    value: 'SVC',
    label: '₡ Salvadoran Colón',
    symbol: '₡',
    locale: 'es-SV',
  },
  {
    value: 'TTD',
    label: 'TT$ Trinidad and Tobago Dollar',
    symbol: 'TT$',
    locale: 'en-TT',
  },
  {
    value: 'XCD',
    label: 'EC$ East Caribbean Dollar',
    symbol: 'EC$',
    locale: 'en-AG',
  },
  {
    value: 'BBD',
    label: 'Bds$ Barbadian Dollar',
    symbol: 'Bds$',
    locale: 'en-BB',
  },
  {
    value: 'JMD',
    label: 'J$ Jamaican Dollar',
    symbol: 'J$',
    locale: 'en-JM',
  },
  {
    value: 'BSD',
    label: 'B$ Bahamian Dollar',
    symbol: 'B$',
    locale: 'en-BS',
  },
  {
    value: 'BZD',
    label: 'BZ$ Belize Dollar',
    symbol: 'BZ$',
    locale: 'en-BZ',
  },
  {
    value: 'GYD',
    label: 'G$ Guyanese Dollar',
    symbol: 'G$',
    locale: 'en-GY',
  },
  {
    value: 'HTG',
    label: 'G Haitian Gourde',
    symbol: 'G',
    locale: 'ht-HT',
  },
  {
    value: 'ANG',
    label: 'ƒ Netherlands Antillean Guilder',
    symbol: 'ƒ',
    locale: 'nl-CW',
  },
  {
    value: 'AWG',
    label: 'ƒ Aruban Florin',
    symbol: 'ƒ',
    locale: 'nl-AW',
  },
  {
    value: 'BMD',
    label: 'BD$ Bermudian Dollar',
    symbol: 'BD$',
    locale: 'en-BM',
  },
  {
    value: 'KYD',
    label: 'CI$ Cayman Islands Dollar',
    symbol: 'CI$',
    locale: 'en-KY',
  },
  {
    value: 'FJD',
    label: 'FJ$ Fijian Dollar',
    symbol: 'FJ$',
    locale: 'en-FJ',
  },
  {
    value: 'PGK',
    label: 'K Papua New Guinean Kina',
    symbol: 'K',
    locale: 'en-PG',
  },
  {
    value: 'SBD',
    label: 'SI$ Solomon Islands Dollar',
    symbol: 'SI$',
    locale: 'en-SB',
  },
  {
    value: 'TOP',
    label: 'T$ Tongan Paʻanga',
    symbol: 'T$',
    locale: 'to-TO',
  },
  {
    value: 'WST',
    label: 'WS$ Samoan Tala',
    symbol: 'WS$',
    locale: 'sm-WS',
  },
  {
    value: 'VUV',
    label: 'VT Vanuatu Vatu',
    symbol: 'VT',
    locale: 'bi-VU',
  },
  {
    value: 'XPF',
    label: 'CFP Franc',
    symbol: '₣',
    locale: 'fr-PF',
  },
  {
    value: 'DJF',
    label: 'Fdj Djiboutian Franc',
    symbol: 'Fdj',
    locale: 'fr-DJ',
  },
  {
    value: 'GNF',
    label: 'FG Guinean Franc',
    symbol: 'FG',
    locale: 'fr-GN',
  },
  {
    value: 'KMF',
    label: 'CF Comorian Franc',
    symbol: 'CF',
    locale: 'fr-KM',
  },
  {
    value: 'MGA',
    label: 'Ar Malagasy Ariary',
    symbol: 'Ar',
    locale: 'mg-MG',
  },
  {
    value: 'MUR',
    label: '₨ Mauritian Rupee',
    symbol: '₨',
    locale: 'en-MU',
  },
  {
    value: 'SCR',
    label: '₨ Seychellois Rupee',
    symbol: '₨',
    locale: 'en-SC',
  },
  {
    value: 'SLL',
    label: 'Le Sierra Leonean Leone',
    symbol: 'Le',
    locale: 'en-SL',
  },
  {
    value: 'SOS',
    label: 'Sh Somali Shilling',
    symbol: 'Sh',
    locale: 'so-SO',
  },
  {
    value: 'TZS',
    label: 'TSh Tanzanian Shilling',
    symbol: 'TSh',
    locale: 'sw-TZ',
  },
  {
    value: 'UGX',
    label: 'USh Ugandan Shilling',
    symbol: 'USh',
    locale: 'en-UG',
  },
  {
    value: 'ZMW',
    label: 'ZK Zambian Kwacha',
    symbol: 'ZK',
    locale: 'en-ZM',
  },
  {
    value: 'NAD',
    label: 'N$ Namibian Dollar',
    symbol: 'N$',
    locale: 'en-NA',
  },
  {
    value: 'MWK',
    label: 'MK Malawian Kwacha',
    symbol: 'MK',
    locale: 'en-MW',
  },
  {
    value: 'BWP',
    label: 'P Botswana Pula',
    symbol: 'P',
    locale: 'en-BW',
  },
  {
    value: 'LSL',
    label: 'L Lesotho Loti',
    symbol: 'L',
    locale: 'en-LS',
  },
  {
    value: 'SZL',
    label: 'L Eswatini Lilangeni',
    symbol: 'L',
    locale: 'en-SZ',
  },
  {
    value: 'GMD',
    label: 'D Gambian Dalasi',
    symbol: 'D',
    locale: 'en-GM',
  },
  {
    value: 'MOP',
    label: 'MOP$ Macanese Pataca',
    symbol: 'MOP$',
    locale: 'zh-MO',
  },
  {
    value: 'STN',
    label: 'Db São Tomé and Príncipe Dobra',
    symbol: 'Db',
    locale: 'pt-ST',
  },
  {
    value: 'ERN',
    label: 'Nfk Eritrean Nakfa',
    symbol: 'Nfk',
    locale: 'ti-ER',
  },
  {
    value: 'CDF',
    label: 'FC Congolese Franc',
    symbol: 'FC',
    locale: 'fr-CD',
  },
  {
    value: 'RWF',
    label: 'RF Rwandan Franc',
    symbol: 'RF',
    locale: 'rw-RW',
  },
  {
    value: 'BIF',
    label: 'FBu Burundian Franc',
    symbol: 'FBu',
    locale: 'fr-BI',
  },
  {
    value: 'AMD',
    label: '֏ Armenian Dram',
    symbol: '֏',
    locale: 'hy-AM',
  },
  {
    value: 'GEL',
    label: '₾ Georgian Lari',
    symbol: '₾',
    locale: 'ka-GE',
  },
  {
    value: 'MDL',
    label: 'L Moldovan Leu',
    symbol: 'L',
    locale: 'ro-MD',
  },
  {
    value: 'ALL',
    label: 'L Albanian Lek',
    symbol: 'L',
    locale: 'sq-AL',
  },
  {
    value: 'MKD',
    label: 'ден Macedonian Denar',
    symbol: 'ден',
    locale: 'mk-MK',
  },
  {
    value: 'RSD',
    label: 'дин Serbian Dinar',
    symbol: 'дин',
    locale: 'sr-RS',
  },
  {
    value: 'BAM',
    label: 'KM Bosnia-Herzegovina Convertible Mark',
    symbol: 'KM',
    locale: 'bs-BA',
  },
  {
    value: 'BYN',
    label: 'Br Belarusian Ruble',
    symbol: 'Br',
    locale: 'be-BY',
  },
  {
    value: 'AZN',
    label: '₼ Azerbaijani Manat',
    symbol: '₼',
    locale: 'az-AZ',
  },
  {
    value: 'TMT',
    label: 'T Turkmenistani Manat',
    symbol: 'T',
    locale: 'tk-TM',
  },
  {
    value: 'TJS',
    label: 'ЅМ Tajikistani Somoni',
    symbol: 'ЅМ',
    locale: 'tg-TJ',
  },
  {
    value: 'KGS',
    label: 'с Kyrgyzstani Som',
    symbol: 'с',
    locale: 'ky-KG',
  },
]
